# Device Arguments

accelerator: cuda               # Device accelerator (e.g., "cuda" for GPU)
num_devices: 1                  # Number of devices (GPUs) to use
distributed_strategy: "auto"    # Distributed training strategy (if applicable)
force_deterministic: False      # Force deterministic behavior
precision: 32                   # Training precision (e.g., "bf16-mixed")
compile: False                  # Compile the model for faster execution
workers: 4                      # Number of workers for data loading


# Model and Training Arguments

project_name: "Embedding-SwinV2-Large-CXL-Open" # WandB project name form: <Function>-<Backbone>-<Dataset>-<Set-Type> eg. Embedding-ResNet50-CXL-Open
run_name: "332-baseline" # Name for this training run form: <Issue Number>-<Purpose> eg. #123-testing-new-data
wandb_tags: ["baseline"]            # WandB tags for experiment tracking
model_name_or_path: "timm/swinv2_large_window12to16_192to256.ms_in22k_ft_in1k"  # Model name or path 
saved_checkpoint_path: "/workspaces/gorillatracker/models/knowledge-distillation"       # Path to a saved model checkpoint (if resuming)
resume: False                     # Resume training from a saved checkpoint can also be a wandb path (wandb:model_id:tag)
fast_dev_run: False               # Enable fast development run
profiler: Null                    # Profiler to use (e.g., "simple", "advanced", "pytorch")
offline: False                    # Enable offline mode for WandB
data_preprocessing_only: False    # Run only data preprocessing
seed: 42                          # Random seed for reproducibility
debug: False                      # Enable debug mode
from_scratch: False               # Train the model from scratch
early_stopping_patience: 6        # Early stopping patience (number of epochs)
embedding_size: 256
dropout_p: 0.5
use_quantization_aware_training: True

weight_decay: 0.5               # Weight decay
beta1: 0.9                      # Adam optimizer's beta1 parameter
beta2: 0.999                    # Adam optimizer's beta2 parameter
epsilon: 1e-7                   # Adam optimizer's epsilon

# L2SP Arguments
l2_alpha: 0.1                       # Alpha for the l2sp loss
l2_beta: 0.01                       # Beta for the l2sp loss
path_to_pretrained_weights: "pretrained_weights/swinv2_large.pth"    # Path to the pretrained weights for the l2sp loss

margin: 1.0                   # Margin for the contrastive loss (triplet loss)
s: 64.0                         # Scale for the softmax losses 

loss_mode: "distillation/offline/response-based"        # Loss modes are "offline", "offline/native", "online/soft", "online/semi-hard", "online/hard", "softmax/arcface" 
teacher_model_wandb_link: "/workspaces/gorillatracker/models/vit_large_gorillas_Embedding-VitLarge-CXL-OpenSet_t6z53vr7.ckpt"


lr_schedule: "exponential"           # Learning rate schedule (e.g., "linear", "cosine", "exponential", "reduce_on_plateau") TODO: add 
warmup_mode: "constant"           # Warmup mode (e.g., "linear", "cosine", "exponential", "constant")
warmup_epochs: 0                # Number of warmup epochs (if 0 no warmup is performed)
initial_lr: 1e-4                # Initial learning rate before warmup(must be > 0.0)
start_lr: 1e-4                  # Learning Rate after warmup at the beginning of 'normal' scheduling
end_lr: 1e-5                    # End learning rate (for the learning rate schedule -> cosine learning rate schedule)


batch_size: 16                  # Training batch size
grad_clip: 1.0                  # Gradient clipping value
gradient_accumulation_steps: 4  # Gradient accumulation steps
max_epochs: 40                  # Training goal (large number)
val_before_training: True       # Perform validation before training
only_val: False                 # Perform only validation
kfold: True                     # Perform kfold cross validation

save_interval: 2                # Model checkpoint save interval as a fraction of total steps
embedding_save_interval: 2      # Embedding save interval

# Config and Data Arguments
# wandb_tags: ["research-template"] # WandB tags for experiment tracking

data_dir: "/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_seed42_square_kfold-5"
dataset_class: "gorillatracker.datasets.kfold_cxl.HardCrossEncounterKFoldCXLDataset"
data_resize_transform: 256
fix_img_size: 256

additional_val_dataset_classes: ["gorillatracker.datasets.bristol.BristolDataset"]
additional_val_data_dirs: ["/workspaces/gorillatracker/data/supervised/bristol/cross_encounter_validation/cropped_frames_square_filtered"]