# Device Arguments

accelerator: cuda               # Device accelerator (e.g., "cuda" for GPU)
num_devices: 1                  # Number of devices (GPUs) to use
distributed_strategy: "auto"    # Distributed training strategy (if applicable)
force_deterministic: True      # Force deterministic behavior
precision: 32            # Training precision (e.g., "bf16-mixed")
compile: False                  # Compile the model for faster execution
workers: 4                     # Number of workers for data loading


# Model and Training Arguments

project_name: "Embedding-SwinV2Large-CXL-Open"  # WandB project name form: <Function>-<Backbone>-<Dataset>-<Set-Type> eg. Embedding-ResNet50-CXL-Open
run_name: "371-combined_arcface_focal_noclsw" # Name for this training run form: <Issue Number>-<Purpose> eg. #123-testing-new-data
wandb_tags: []            # WandB tags for experiment tracking
model_name_or_path: "SwinV2LargeWrapper"  # Model name or path 
saved_checkpoint_path: Null       # Path to a saved model checkpoint (if resuming)
resume: False                     # Resume training from a saved checkpoint can also be a wandb path (wandb:model_id:tag)
fast_dev_run: False               # Enable fast development run
profiler: Null                    # Profiler to use (e.g., "simple", "advanced", "pytorch")
offline: False                    # Enable offline mode for WandB
data_preprocessing_only: False    # Run only data preprocessing
seed: 42                          # Random seed for reproducibility
debug: False                      # Enable debug mode
from_scratch: False               # Train the model from scratch
early_stopping_patience: 50        # Early stopping patience (number of epochs)
embedding_size: 256
dropout_p: 0.32

# Optimizer Arguments
weight_decay: 1.0               # Weight decay if l2sp regularisation is used this is set to 0.0
beta1: 0.9                      # Adam optimizer's beta1 parameter
beta2: 0.999                    # Adam optimizer's beta2 parameter
epsilon: 1e-7                   # Adam optimizer's epsilon

# L2SP Arguments
l2_alpha: 0.1                       # Alpha for the l2sp loss - 0.1
l2_beta: 0.01                       # Beta for the l2sp loss - 0.01
path_to_pretrained_weights: "pretrained_weights/swinv2_large.pth"   # Path to the pretrained weights for the l2sp loss

k_subcenters: 1
margin: 1.0                         # Margin for the contrastive loss (triplet loss)
s: 64.0                             # Scale for the softmax losses 
delta_t: 50                         # Delta t for the vpl loss
mem_bank_start_epoch: 10            # Epoch to start using the memory bank
lambda_membank: 0.5                 # Lambda for the memory bank loss
use_focal_loss: false                # Use focal loss
label_smoothing: 0.05                # Label smoothing value
loss_mode: "softmax/arcface/combined/l2sp"          # Loss modes are "offline", "offline/native", "online/soft", "online/semi-hard", "online/hard", "softmax/arcface" and "softmax/vpl". 
                                    # Each loss is availible with l2sp regularisation just add /l2sp to the loss mode
use_class_weights: False                # Use class weights for the loss
use_dist_term: False                     # Use the distance term for the loss

lr_schedule: "cosine"           # Learning rate schedule (e.g., "linear", "cosine", "exponential", "reduce_on_plateau") TODO: add 
warmup_mode: "cosine"           # Warmup mode (e.g., "linear", "cosine", "exponential", "constant")
warmup_epochs: 5               # Number of warmup epochs (if 0 no warmup is performed)
initial_lr: 1e-5                # Initial learning rate before warmup(must be > 0.0)
start_lr: 1e-5                  # Learning Rate after warmup at the beginning of 'normal' scheduling
end_lr: 1e-7                    # End learning rate (for the learning rate schedule -> cosine learning rate schedule)


batch_size: 32                 # Training batch size
grad_clip: 1.0                 # Gradient clipping value
gradient_accumulation_steps: 4  # Gradient accumulation steps
max_epochs: 200                  # Training goal (large number)
val_before_training: True       # Perform validation before training
only_val: False                 # Perform only validation
kfold: False                     # Perform kfold cross validation

save_interval: 50                # Model checkpoint save interval as a fraction of total steps
embedding_save_interval: 50      # Embedding save interval
save_model_to_wandb: True       # Save the model to wandb
check_val_every_n_epoch: 10      # Perform validation every n epochs

# Config and Data Arguments
# wandb_tags: ["research-template"] # WandB tags for experiment tracking

data_dir: "/workspaces/gorillatracker/data/splits/ground_truth-cxl-face_images-openset-reid-val-0-test-0-mintraincount-3-seed-42-train-50-val-25-test-25"
dataset_class: "gorillatracker.datasets.cxl.CXLDataset"
data_resize_transform: 224