# Device Arguments

accelerator: cuda               # Device accelerator (e.g., "cuda" for GPU)
num_devices: 1                  # Number of devices (GPUs) to use
distributed_strategy: "auto"    # Distributed training strategy (if applicable)
force_deterministic: True      # Force deterministic behavior
precision: 32           # Training precision (e.g., "bf16-mixed")
compile: False                  # Compile the model for faster execution
workers: 10                      # Number of workers for data loading


# Model and Training Arguments

project_name: "Embedding-DinoV2-SSL-Test"
run_name: "523-test-kfold-val" # Name for this training run form: <Issue Number>-<Purpose> eg. #123-testing-new-data
wandb_tags: ["dinov2", "base"]            # WandB tags for experiment tracking
model_name_or_path: "timm/vit_large_patch14_dinov2.lvd142m" # Model name or path 
saved_checkpoint_path: Null     # Path to a saved model checkpoint (if resuming)
resume: False                   # Resume training from a saved checkpoint can also be a wandb path (wandb:model_id:tag)
fast_dev_run: False             # Enable fast development run
profiler: Null                  # Profiler to use (e.g., "simple", "advanced", "pytorch")
offline: False                  # Enable offline mode for WandB
data_preprocessing_only: False  # Run only data preprocessing
seed: 42                        # Random seed for reproducibility
debug: False                    # Enable debug mode
from_scratch: False             # Train the model from scratch
embedding_size: 256
dropout_p: 0.36                 # Dropout probability
early_stopping_patience: 10     # Early stopping patience

weight_decay: 0.4              # Weight decay
beta1: 0.9                      # Adam optimizer's beta1 parameter
beta2: 0.999                    # Adam optimizer's beta2 parameter
epsilon: 1e-7                   # Adam optimizer's epsilon

# L2SP Arguments
l2_alpha: 0.095                      # Alpha for the l2sp loss
l2_beta: 0.022                       # Beta for the l2sp loss
path_to_pretrained_weights: "pretrained_weights/ViT_Large_DinoV2.pth"     # Path to the pretrained weights for the l2sp loss

margin: 0.83                   # Margin for the contrastive loss (triplet loss)
s: 64.0                         # Scale for the softmax losses 
loss_mode: "offline/native"        # Loss modes are "offline", "offline/native", "online/soft", "online/semi-hard", "online/hard", "softmax/arcface" and "softmax/vpl"

lr_schedule: "exponential"           # Learning rate schedule (e.g., "linear", "cosine", "exponential", "reduce_on_plateau") TODO: add 
warmup_mode: "constant"           # Warmup mode (e.g., "linear", "cosine", "exponential", "constant")
warmup_epochs: 0                # Number of warmup epochs (if 0 no warmup is performed)
initial_lr: 6e-4                # Initial learning rate before warmup(must be > 0.0)
start_lr: 2e-7                 # Learning Rate after warmup at the beginning of 'normal' scheduling
end_lr: 1e-8                    # End learning rate (for the learning rate schedule -> cosine learning rate schedule)

batch_size: 8                # Training batch size
grad_clip: 1.0                  # Gradient clipping value
gradient_accumulation_steps: 1  # Gradient accumulation steps
max_epochs: 1                  # Training goal (large number)
val_before_training: True       # Perform validation before training
only_val: False                 # Perform only validation

val_check_interval: 0.25         # Validation check interval as a fraction of total steps
save_interval: 2                # Model checkpoint save interval as a fraction of total steps
embedding_save_interval: 100      # Embedding save interval
knn_with_train: False   
save_model_to_wandb: False 
n_samples: 6 

# Config and Data Arguments
# wandb_tags: ["research-template"] # WandB tags for experiment tracking

use_ssl: True
split_path: "/workspaces/gorillatracker/data/splits/SSL/SSL-1k-woCXL_1k-100-1k_split_20240716_1037.pkl"
feature_types: ["face_90"]
negative_mining: "overlapping"
data_resize_transform: 518

dataset_names: ["ssl", "cxl_kfold"]
additional_val_dataset_classes: [gorillatracker.datasets.cxl.ValKFoldCXLDataset]
additional_val_data_dirs: [/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_seed42_square_kfold-5]
dataset_class: "gorillatracker.datasets.ssl.SSLDataset"
data_dir: "/workspaces/gorillatracker/cropped-images/2024-04-18"