# https://wandb.ai/gorillas/Embedding-DinoV2-SSL-Face-squared/runs/2ujvfr6s/overview
# Device Arguments
accelerator: cuda               # Device accelerator (e.g., "cuda" for GPU)
num_devices: 1                  # Number of devices (GPUs) to use
distributed_strategy: "auto"    # Distributed training strategy (if applicable)
force_deterministic: True      # Force deterministic behavior
precision: 32                   # Training precision (e.g., "bf16-mixed")
compile: False                  # Compile the model for faster execution
workers: 20                      # Number of workers for data loading

# Model and Training Arguments

project_name: "Embedding-ViTLarge-SSL-Split" # WandB project name form: <Function>-<Backbone>-<Dataset>-<Set-Type> eg. Embedding-ResNet50-CXL-Open
run_name: "ba-ben-best-split" # Name for this training run form: <Issue Number>-<Purpose> eg. #123-testing-new-data
wandb_tags: ["test"]            # WandB tags for experiment tracking
fix_img_size: 224
model_name_or_path: "timm/vit_large_patch14_dinov2.lvd142m"  # Model name or path 
saved_checkpoint_path: Null       # Path to a saved model checkpoint (if resuming)
resume: False                     # Resume training from a saved checkpoint can also be a wandb path (wandb:model_id:tag)
fast_dev_run: False               # Enable fast development run
profiler: Null                    # Profiler to use (e.g., "simple", "advanced", "pytorch")
offline: False                    # Enable offline mode for WandB
data_preprocessing_only: False    # Run only data preprocessing
seed: 42                          # Random seed for reproducibility
debug: False                      # Enable debug mode
from_scratch: False               # Train the model from scratch
early_stopping_patience: 3        # Early stopping patience (number of epochs)
stop_saving_metric_name: "cxl-all-val/val/embeddings/knn5_crossvideo_cos/accuracy"
stop_saving_metric_mode: "max"
embedding_size: 256
dropout_p: 0.123

# Optimizer Arguments
weight_decay: 0.2              # Weight decay if l2sp regularisation is used this is set to 0.0
beta1: 0.9                      # Adam optimizer's beta1 parameter
beta2: 0.999                    # Adam optimizer's beta2 parameter
epsilon: 1e-7                   # Adam optimizer's epsilon

# L2SP Arguments
l2_alpha: 0.01                       # Alpha for the l2sp loss
l2_beta: 0.01                      # Beta for the l2sp loss
path_to_pretrained_weights: "pretrained_weights/vit_large_patch14_dinov2_lvd142m.pth"    # Path to the pretrained weights for the l2sp loss

# NTXent Arguments
temperature: 0.035
memory_bank_size: 0

margin: 0.77                         # Margin for the contrastive loss (triplet loss)
s: 64.0                             # Scale for the softmax losses 
loss_mode: "offline/native" # Loss modes are "offline", "offline/native", "online/soft", "online/semi-hard", "online/hard", "softmax/arcface"
                                    # Each loss is availible with l2sp regularisation just add /l2sp to the loss mode


lr_schedule: "cosine"           # Learning rate schedule (e.g., "linear", "cosine", "exponential", "reduce_on_plateau") TODO: add 
warmup_mode: "constant"           # Warmup mode (e.g., "linear", "cosine", "exponential", "constant")
warmup_epochs: 0                # Number of warmup epochs (if 0 no warmup is performed)
initial_lr: 1e-6                # Initial learning rate before warmup(must be > 0.0)
start_lr: 1e-6                  # Learning Rate after warmup at the beginning of 'normal' scheduling
end_lr: 1e-8                    # End learning rate (for the learning rate schedule -> cosine learning rate schedule)
stepwise_schedule: True
lr_interval: 0.5

batch_size: 8                  # Training batch size
grad_clip: 1.0                  # Gradient clipping value
gradient_accumulation_steps: 1  # Gradient accumulation steps
max_epochs: 20                  # Training goal (large number)
val_before_training: True       # Perform validation before training
only_val: False                 # Perform only validation

val_check_interval: 0.5
save_interval: 2                # Model checkpoint save interval as a fraction of total steps
embedding_save_interval: 1      # Embedding save interval
knn_with_train: False    
save_model_to_wandb: False       

# Config and Data Arguments
# wandb_tags: ["research-template"] # WandB tags for experiment tracking
use_ssl: True
# split_path: "/workspaces/gorillatracker/data/splits/SSL/SSL-10k-woCXL_10k-100-1000_split_20240716_1032.pkl"
split_path: "/workspaces/gorillatracker/data/splits/SSL/sweep/20k-SSL-Video-Split_2024-04-18_percentage-95-5-0_split_20240816_0850.pkl"
feature_types: ["face_45"]
tff_selection: "movement"
negative_mining: "overlapping"  
movement_delta: 0.03
n_samples: 10
width_range: [100, 10000]
height_range: [100, 10000]
forced_train_image_count: 6400 # force maximum number of training images

data_resize_transform: 224

additional_val_dataset_classes: [
        gorillatracker.datasets.cxl.CXLDataset, 
        gorillatracker.datasets.cxl.CXLDataset, 
        gorillatracker.datasets.cxl.CXLDataset, 
        gorillatracker.datasets.bristol.BristolDataset, 
        gorillatracker.datasets.cxl.ValKFoldCXLDataset
                          ]
additional_val_data_dirs: [
        "/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_square_val_50_test_50/val", 
        "/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_square_val_50_test_50/test", 
        "/workspaces/gorillatracker/data/supervised/cxl_all/face_images_square", 
        "/workspaces/gorillatracker/data/supervised/bristol/cross_encounter_validation/cropped_frames_square_filtered", 
        "/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_seed42_square_kfold-5"
                          ]
dataset_names: ["ssl", "cxl-all-val", "cxl-all-test", "cxl-all", "bristol", "cxl-kfold"]
dataset_class: "gorillatracker.datasets.ssl.SSLDataset"
data_dir: "/workspaces/gorillatracker/cropped-images-squared/2024-04-18"