services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "REDACTED"
    ports:
      - "5432:5432"
    volumes:
      - /mnt/vast-gorilla/pgdata:/var/lib/postgresql/data
    restart: always
