name: Lint & Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

# permissions:
#   contents: write

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy

      # - name: Format with black and isort
      #   run: |
      #     make format

      # fail if lint fails
      - name: Lint 
        run: |
          make lint
          make mypy
      # else commit the autoformatted code fixes
      # - name: Check for modified files
      #   id: git-check
      #   run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      # # NOTE(liamvdv): don't autofix here.
      # - name: Push changes
      #   if: steps.git-check.outputs.modified == 'true'
      #   run: |
      #     BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
      #     git checkout $BRANCH_NAME
      #     git config --global user.name 'BananaPealer'
      #     git config --global user.email 'liamvdv@users.noreply.github.com'
      #     git commit -am "Automated changes"
      #     # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      #     git push origin $BRANCH_NAME

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/mamba-org/setup-micromamba
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment-key: micromamba-env-${{ hashFiles('environment.yml') }}
          init-shell: >-
            bash

      - name: Install gorillatracker
        run: pip install .
        shell: micromamba-shell {0}

      - name: Run tests
        run: |
          make tests
        shell: micromamba-shell {0}
