name: Format, Lint & Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy

      - name: Format with black and isort
        run: |
          make format

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'BananaPealer'
          git config --global user.email 'liamvdv@users.noreply.github.com'
          git commit -am "Automated changes"

      - name: Lint
        run: |
          make lint

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/mamba-org/setup-micromamba
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          init-shell: >-
            bash

      - name: Install gorillatracker
        run: pip install .
        shell: micromamba-shell {0}

      - name: Run tests
        run: |
          make tests
        shell: micromamba-shell {0}
