name: Nightly WandB Cleanup

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wandb pydantic typer
    - name: Create deletion plan
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_SECRET }}
      run: |
        python3 scripts/clean_wandb.py process --output /tmp/wandb_cleanup.json
        cat /tmp/wandb_cleanup.json
    - name: Apply deletion plan
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_SECRET }}
      run: |
        # TODO(liamvdv): keep disabled until review complete; then "yes\nyes"
        echo -e "yes\nno" | python3 scripts/clean_wandb.py apply /tmp/wandb_cleanup.json
